#Config file for Offline Speech Recognition server and audio recorder

############### Audio Recorder configuration ################

config_recorder: {
    audio_record_dir: '../misc/records',
    convert_rate: 16000,
    convert_width: 2,
    tts_service: 'action_TTS_MIMIC',
    ajusting_ambient_noise_duration: 0.5,
    listen_timeout: 5,
    listen_phrase_time_limit: 5
}


############### Speech Recognition servers configuration ##########

config: {
    Receptionist: {
        hmm: "../config/model/en-us",
        dict: '../misc/receptionist/asr.dict',
        kwlist: '../misc/receptionist/asr.kwlist',
        gram: "../misc/receptionist/asr",
        grammar: "asr",
        rule: "rule",
        database: {
            "names": "../misc/receptionist/corpus_names.txt",
            "age": "../misc/receptionist/corpus_age.txt",
            "drinks": "../misc/receptionist/corpus_boisson.txt",
            "confirmation": "../misc/receptionist/corpus_confirmation.txt",
            "next": "../misc/receptionist/corpus_next.txt"
        }
    },
    Clean_up: {
        hmm: "../config/model/en-us",
        dict: '../misc/cleanup/cleanup.dict',
        kwlist: '../misc/cleanup/cleanup.kwlist',
        gram: "../misc/cleanup/cleanup",
        grammar: "cleanup",
        rule: "cleanupRule",
        database: {
            "room": "../misc/cleanup/room.txt",
            "confirmation": "../misc/cleanup/confirmation.txt"
        }
    }
}

parser_action_database: {
    Receptionist: {
        askAge: 'age',
        askDrink: 'drinks',
        askName: 'names',
        confirm: 'confirmation',
        askOpenDoor: "next"
    },
    Clean_up: {
        askRoom: 'room',
        confirm: 'confirmation'
    }
}

############### ROS configuration ################

stt_server_name: "STT_action_server"

tts_server_name: "action_TTS_MIMIC"

test_mode: False

socketIO_ip: "http://127.0.0.1"

socketIO_port: 5001